        <html><head></head><body>
        <h1>Report for alsa-lib on toolchain
            <a href="index.html">android</a>
        </h1>
        <p>Return code: 1</p>
        <p>Time to run: 00:00:24</p>
        <p>Log output:</p>
        <code><pre><docker run --rm -v /tuscan_data --volumes-from tuscan_data -v /sources --volumes-from sources -v /var/cache/pacman/pkg --volumes-from pkg_cache_android -v logs:/logs make_package_container --sources-directory /sources --shared-directory /tuscan_data alsa-lib
:: Synchronizing package databases...
downloading repo.db...
downloading core.db...
downloading extra.db...
downloading community.db...
Found 2116 packages in cache
===> sudo -u tuscan makepkg --nobuild --syncdeps --skipinteg --skippgpcheck --skipchecksums --noconfirm --nocolor --log --noprogressbar --nocheck
==> Making package: alsa-lib 1.0.29-1 (Sat Nov 14 00:01:11 UTC 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Packages (2) sqlite-3.9.2-1  python2-2.7.10-2

Total Installed Size:  75.75 MiB

:: Proceed with installation? [Y/n] 
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
installing sqlite...
installing python2...
Optional dependencies for python2
    tk: for IDLE
    python2-setuptools
    python2-pip
==> Retrieving sources...
  -> Downloading alsa-lib-1.0.29.tar.bz2...
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Extracting alsa-lib-1.0.29.tar.bz2 with bsdtar
==> Sources are ready.
Copied source directory to /sources/alsa-lib
Traceback (most recent call last):
  File "/build/make_package.py", line 215, in <module>
    main()
  File "/build/make_package.py", line 212, in main
    result = copy_and_build(args)
  File "/build/make_package.py", line 118, in copy_and_build
    copytree(permanent_source_dir, build_dir)
  File "/usr/lib/python3.5/shutil.py", line 353, in copytree
    raise Error(errors)
shutil.Error: [('/sources/alsa-lib/src/alsa-lib-1.0.29/include/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa', '/tmp/alsa-lib/src/alsa-lib-1.0.29/include/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa', "[Errno 40] Too many levels of symbolic links: '/sources/alsa-lib/src/alsa-lib-1.0.29/include/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa/alsa'")]></pre></code>
        </body></html>
